
# WOOFY SECURITY GUARDRAILS - AUTO-APPLIED
import os
import sys
import logging

# Disable AWS credential logging
for logger_name in ['boto3', 'botocore', 'urllib3', 's3transfer']:
    logging.getLogger(logger_name).setLevel(logging.CRITICAL)

# Suppress credential discovery
os.environ['AWS_DEFAULT_OUTPUT'] = 'json'
os.environ['AWS_CLI_FILE_ENCODING'] = 'UTF-8'

# Import security guardrails
try:
    from security_guardrails import SecurityGuardrails
    SecurityGuardrails.secure_log("Security guardrails active")
except ImportError:
    pass

import os
from pathlib import Path

def update_env_file():
    """Interactive script to update .env file with credentials"""
    
    print("WOOFY McWOOFSON: Environment Credentials Setup")
    print("=" * 50)
    
    # Check if .env exists, if not copy from example
    env_file = Path('.env')
    env_example = Path('.env.example')
    
    if not env_file.exists() and env_example.exists():
        print("Creating .env from .env.example...")
        with open(env_example, 'r') as src, open(env_file, 'w') as dst:
            dst.write(src.read())
        print("SUCCESS: .env file created")
    
    # Read current .env
    env_vars = {}
    if env_file.exists():
        with open(env_file, 'r') as f:
            for line in f:
                if '=' in line and not line.startswith('#'):
                    key, value = line.strip().split('=', 1)
                    env_vars[key] = value
    
    # Credentials to update
    credentials = {
        'PERPLEXITY_API_KEY': 'Enter your Perplexity API key',
        'AWS_ACCESS_KEY_ID': 'Enter your AWS Access Key ID',
        'AWS_SECRET_ACCESS_KEY': 'Enter your AWS Secret Access Key',
        'GITHUB_TOKEN': 'Enter your GitHub Personal Access Token (optional - already set)',
        'API_KEY': 'Enter any other API key (optional)'
    }
    
    print("\nEnter your credentials (press Enter to skip):")
    print("-" * 50)
    
    updated = False
    for key, prompt in credentials.items():
        current_value = env_vars.get(key, '')
        
        if key == 'GITHUB_TOKEN' and current_value and not current_value.startswith('your_'):
            print(f"{key}: Already set (keeping current value)")
            continue
            
        if current_value.startswith('your_'):
            current_value = ''
        
        new_value = input(f"{prompt}: ").strip()
        
        if new_value:
            env_vars[key] = new_value
            updated = True
            print(f"SUCCESS: {key} updated")
        elif current_value:
            print(f"KEEPING: {key} (current value)")
        else:
            print(f"SKIPPED: {key}")
    
    # Write updated .env file
    if updated:
        with open(env_file, 'w') as f:
            f.write("# WOOFY McWOOFSON Environment Variables\n")
            f.write("# Generated by update_env_credentials.py\n\n")
            
            for key, value in env_vars.items():
                f.write(f"{key}={value}\n")
            
            # Add any missing keys with placeholders
            for key in credentials.keys():
                if key not in env_vars:
                    f.write(f"{key}=your_{key.lower()}_here\n")
        
        print(f"\nSUCCESS: .env file updated with {sum(1 for v in env_vars.values() if v and not v.startswith('your_'))} credentials")
    else:
        print("\nNO CHANGES: .env file not modified")
    
    # Show current status
    print("\nCURRENT STATUS:")
    print("-" * 30)
    for key in credentials.keys():
        value = env_vars.get(key, 'NOT SET')
        if value and not value.startswith('your_'):
            status = f"SET ({value[:10]}...)" if len(value) > 10 else "SET"
        else:
            status = "NOT SET"
        print(f"{key}: {status}")
    
    print(f"\nENV FILE: {env_file.absolute()}")
    return True

def quick_perplexity_setup():
    """Quick setup for just Perplexity API key"""
    print("\nQUICK PERPLEXITY SETUP")
    print("-" * 30)
    
    api_key = input("Enter your Perplexity API key: ").strip()
    
    if api_key:
        # Update .env
        env_content = f"""# WOOFY McWOOFSON - Perplexity Integration
PERPLEXITY_API_KEY={api_key}
PERPLEXITY_MODEL=llama-3.1-sonar-small-128k-online
PERPLEXITY_MAX_TOKENS=1000
PERPLEXITY_TEMPERATURE=0.7
"""
        
        with open('.env.perplexity', 'w') as f:
            f.write(env_content)
        
        print("SUCCESS: Perplexity credentials saved to .env.perplexity")
        return True
    
    return False

def main():
    print("Choose setup option:")
    print("1. Full credentials setup (.env)")
    print("2. Quick Perplexity setup only")
    
    choice = input("Enter choice (1 or 2): ").strip()
    
    if choice == '1':
        update_env_file()
    elif choice == '2':
        quick_perplexity_setup()
    else:
        print("Invalid choice")

if __name__ == "__main__":
    main()