name: "Woofy: Compliance Check"
on:
  pull_request:

jobs:
  compliance:
    runs-on: ubuntu-latest
    steps:
      - name: 🐾 Checkout code
        uses: actions/checkout@v6
      - name: 🐾 Run security scan
        run: npm run security-check